# environment variable keys
FRONTEND_ENDPOINT_KEY="FRONTEND_ENDPOINT"

# app secret key
SECRETKEY_KEY='SECRET_KEY'

# for oatuh setup
GOOGLE_CLIENT_ID_KEY='GOOGLE_CLIENT_ID'
GOOGLE_CLIENT_SECRET_KEY='GOOGLE_CLIENT_SECRET'
GOOGLE_DISCOVERY_URL_KEY='GOOGLE_DISCOVERY_URL'
OAUTHLIB_INSECURE_TRANSPORT_KEY='OAUTHLIB_INSECURE_TRANSPORT'
OAUTHLIB_RELAX_TOKEN_SCOPE_KEY='OAUTHLIB_RELAX_TOKEN_SCOPE'
BLUE_PRINT_SCOPE_PROFILE='profile'
BLUE_PRINT_SCOPE_EMAIL='email'

# for google data
GOOGLE_ID_KEY='sub'
GOOGLE_EMAIL_KEY='email'
GOOGLE_NAME_KEY='name'
GOOGLE_PICTURE_KEY='picture'

# google token keys
GOOGLE_ACCESS_TOKEN_KEY='access_token'
GOOGLE_ID_TOKEN_KEY='id_token'

# for sql
SQL_ROW_COUNT_KEY='count(*)'
SQL_COUNT_USER_QUERY='SELECT count(*) FROM user WHERE user_id = {}'
SQL_GET_USER_BY_ID='SELECT * FROM user WHERE user_id = {}'